# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/dave/misc-projects/rftool-fpga/projects/rx_only/rx_only.srcs/sources_1/ip/sys_pll/sys_pll.xci
# IP: The module: 'sys_pll' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/dave/misc-projects/rftool-fpga/projects/rx_only/rx_only.srcs/sources_1/ip/sys_pll/sys_pll_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'sys_pll'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/dave/misc-projects/rftool-fpga/projects/rx_only/rx_only.srcs/sources_1/ip/sys_pll/sys_pll.xdc
# XDC: The top module name and the constraint reference have the same name: 'sys_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/dave/misc-projects/rftool-fpga/projects/rx_only/rx_only.srcs/sources_1/ip/sys_pll/sys_pll_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sys_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: /home/dave/misc-projects/rftool-fpga/projects/rx_only/rx_only.srcs/sources_1/ip/sys_pll/sys_pll.xci
# IP: The module: 'sys_pll' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/dave/misc-projects/rftool-fpga/projects/rx_only/rx_only.srcs/sources_1/ip/sys_pll/sys_pll_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'sys_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/dave/misc-projects/rftool-fpga/projects/rx_only/rx_only.srcs/sources_1/ip/sys_pll/sys_pll.xdc
# XDC: The top module name and the constraint reference have the same name: 'sys_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/dave/misc-projects/rftool-fpga/projects/rx_only/rx_only.srcs/sources_1/ip/sys_pll/sys_pll_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sys_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
