# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/dave/misc-projects/rftool-fpga/projects/rx_tx_gen/rx_tx_gen.srcs/sources_1/ip/sg_ila/sg_ila.xci
# IP: The module: 'sg_ila' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/dave/misc-projects/rftool-fpga/projects/rx_tx_gen/rx_tx_gen.srcs/sources_1/ip/sg_ila/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'sg_ila'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/dave/misc-projects/rftool-fpga/projects/rx_tx_gen/rx_tx_gen.srcs/sources_1/ip/sg_ila/sg_ila_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sg_ila'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/dave/misc-projects/rftool-fpga/projects/rx_tx_gen/rx_tx_gen.srcs/sources_1/ip/sg_ila/sg_ila.xci
# IP: The module: 'sg_ila' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/dave/misc-projects/rftool-fpga/projects/rx_tx_gen/rx_tx_gen.srcs/sources_1/ip/sg_ila/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'sg_ila'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/dave/misc-projects/rftool-fpga/projects/rx_tx_gen/rx_tx_gen.srcs/sources_1/ip/sg_ila/sg_ila_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sg_ila'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
