# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/dave/misc-projects/rftool-fpga/projects/rx_only/rx_only.srcs/sources_1/ip/response_fifo/response_fifo.xci
# IP: The module: 'response_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/dave/misc-projects/rftool-fpga/projects/rx_only/rx_only.srcs/sources_1/ip/response_fifo/response_fifo/response_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'response_fifo'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/dave/misc-projects/rftool-fpga/projects/rx_only/rx_only.srcs/sources_1/ip/response_fifo/response_fifo/response_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'response_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/dave/misc-projects/rftool-fpga/projects/rx_only/rx_only.srcs/sources_1/ip/response_fifo/response_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'response_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/dave/misc-projects/rftool-fpga/projects/rx_only/rx_only.srcs/sources_1/ip/response_fifo/response_fifo.xci
# IP: The module: 'response_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/dave/misc-projects/rftool-fpga/projects/rx_only/rx_only.srcs/sources_1/ip/response_fifo/response_fifo/response_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'response_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/dave/misc-projects/rftool-fpga/projects/rx_only/rx_only.srcs/sources_1/ip/response_fifo/response_fifo/response_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'response_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/dave/misc-projects/rftool-fpga/projects/rx_only/rx_only.srcs/sources_1/ip/response_fifo/response_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'response_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
