# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -msgmgr_mode ooc_run
create_project -in_memory -part xc7a50tftg256-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/dave/misc-projects/rftool-fpga/projects/rx_only/rx_only.cache/wt [current_project]
set_property parent.project_path /home/dave/misc-projects/rftool-fpga/projects/rx_only/rx_only.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo /home/dave/misc-projects/rftool-fpga/projects/rx_only/rx_only.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_ip -quiet /home/dave/misc-projects/rftool-fpga/projects/rx_only/rx_only.srcs/sources_1/ip/response_fifo/response_fifo.xci
set_property is_locked true [get_files /home/dave/misc-projects/rftool-fpga/projects/rx_only/rx_only.srcs/sources_1/ip/response_fifo/response_fifo.xci]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

set cached_ip [config_ip_cache -export -no_bom -use_project_ipc -dir /home/dave/misc-projects/rftool-fpga/projects/rx_only/rx_only.runs/response_fifo_synth_1 -new_name response_fifo -ip [get_ips response_fifo]]

if { $cached_ip eq {} } {

synth_design -top response_fifo -part xc7a50tftg256-2 -mode out_of_context

#---------------------------------------------------------
# Generate Checkpoint/Stub/Simulation Files For IP Cache
#---------------------------------------------------------
catch {
 write_checkpoint -force -noxdef -rename_prefix response_fifo_ response_fifo.dcp

 set ipCachedFiles {}
 write_verilog -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ response_fifo_stub.v
 lappend ipCachedFiles response_fifo_stub.v

 write_vhdl -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ response_fifo_stub.vhdl
 lappend ipCachedFiles response_fifo_stub.vhdl

 write_verilog -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ response_fifo_sim_netlist.v
 lappend ipCachedFiles response_fifo_sim_netlist.v

 write_vhdl -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ response_fifo_sim_netlist.vhdl
 lappend ipCachedFiles response_fifo_sim_netlist.vhdl

 config_ip_cache -add -dcp response_fifo.dcp -move_files $ipCachedFiles -use_project_ipc -ip [get_ips response_fifo]
}

rename_ref -prefix_all response_fifo_

write_checkpoint -force -noxdef response_fifo.dcp

catch { report_utilization -file response_fifo_utilization_synth.rpt -pb response_fifo_utilization_synth.pb }

if { [catch {
  file copy -force /home/dave/misc-projects/rftool-fpga/projects/rx_only/rx_only.runs/response_fifo_synth_1/response_fifo.dcp /home/dave/misc-projects/rftool-fpga/projects/rx_only/rx_only.srcs/sources_1/ip/response_fifo/response_fifo.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  write_verilog -force -mode synth_stub /home/dave/misc-projects/rftool-fpga/projects/rx_only/rx_only.srcs/sources_1/ip/response_fifo/response_fifo_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub /home/dave/misc-projects/rftool-fpga/projects/rx_only/rx_only.srcs/sources_1/ip/response_fifo/response_fifo_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim /home/dave/misc-projects/rftool-fpga/projects/rx_only/rx_only.srcs/sources_1/ip/response_fifo/response_fifo_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim /home/dave/misc-projects/rftool-fpga/projects/rx_only/rx_only.srcs/sources_1/ip/response_fifo/response_fifo_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}


} else {


if { [catch {
  file copy -force /home/dave/misc-projects/rftool-fpga/projects/rx_only/rx_only.runs/response_fifo_synth_1/response_fifo.dcp /home/dave/misc-projects/rftool-fpga/projects/rx_only/rx_only.srcs/sources_1/ip/response_fifo/response_fifo.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  file rename -force /home/dave/misc-projects/rftool-fpga/projects/rx_only/rx_only.runs/response_fifo_synth_1/response_fifo_stub.v /home/dave/misc-projects/rftool-fpga/projects/rx_only/rx_only.srcs/sources_1/ip/response_fifo/response_fifo_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force /home/dave/misc-projects/rftool-fpga/projects/rx_only/rx_only.runs/response_fifo_synth_1/response_fifo_stub.vhdl /home/dave/misc-projects/rftool-fpga/projects/rx_only/rx_only.srcs/sources_1/ip/response_fifo/response_fifo_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force /home/dave/misc-projects/rftool-fpga/projects/rx_only/rx_only.runs/response_fifo_synth_1/response_fifo_sim_netlist.v /home/dave/misc-projects/rftool-fpga/projects/rx_only/rx_only.srcs/sources_1/ip/response_fifo/response_fifo_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  file rename -force /home/dave/misc-projects/rftool-fpga/projects/rx_only/rx_only.runs/response_fifo_synth_1/response_fifo_sim_netlist.vhdl /home/dave/misc-projects/rftool-fpga/projects/rx_only/rx_only.srcs/sources_1/ip/response_fifo/response_fifo_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

}; # end if cached_ip 

if {[file isdir /home/dave/misc-projects/rftool-fpga/projects/rx_only/rx_only.ip_user_files/ip/response_fifo]} {
  catch { 
    file copy -force /home/dave/misc-projects/rftool-fpga/projects/rx_only/rx_only.srcs/sources_1/ip/response_fifo/response_fifo_stub.v /home/dave/misc-projects/rftool-fpga/projects/rx_only/rx_only.ip_user_files/ip/response_fifo
  }
}

if {[file isdir /home/dave/misc-projects/rftool-fpga/projects/rx_only/rx_only.ip_user_files/ip/response_fifo]} {
  catch { 
    file copy -force /home/dave/misc-projects/rftool-fpga/projects/rx_only/rx_only.srcs/sources_1/ip/response_fifo/response_fifo_stub.vhdl /home/dave/misc-projects/rftool-fpga/projects/rx_only/rx_only.ip_user_files/ip/response_fifo
  }
}
