# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a50tftg256-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/dave/misc-projects/rftool-fpga/projects/rx_only/rx_only.cache/wt [current_project]
set_property parent.project_path /home/dave/misc-projects/rftool-fpga/projects/rx_only/rx_only.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo /home/dave/misc-projects/rftool-fpga/projects/rx_only/rx_only.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files -quiet /home/dave/misc-projects/rftool-fpga/projects/rx_only/rx_only.srcs/sources_1/ip/command_fifo/command_fifo.dcp
set_property used_in_implementation false [get_files /home/dave/misc-projects/rftool-fpga/projects/rx_only/rx_only.srcs/sources_1/ip/command_fifo/command_fifo.dcp]
add_files -quiet /home/dave/misc-projects/rftool-fpga/projects/rx_only/rx_only.srcs/sources_1/ip/response_fifo/response_fifo.dcp
set_property used_in_implementation false [get_files /home/dave/misc-projects/rftool-fpga/projects/rx_only/rx_only.srcs/sources_1/ip/response_fifo/response_fifo.dcp]
add_files -quiet /home/dave/misc-projects/rftool-fpga/projects/rx_only/rx_only.srcs/sources_1/ip/rx_packet_fifo/rx_packet_fifo.dcp
set_property used_in_implementation false [get_files /home/dave/misc-projects/rftool-fpga/projects/rx_only/rx_only.srcs/sources_1/ip/rx_packet_fifo/rx_packet_fifo.dcp]
add_files -quiet /home/dave/misc-projects/rftool-fpga/projects/rx_only/rx_only.srcs/sources_1/ip/iq_sample_fifo/iq_sample_fifo.dcp
set_property used_in_implementation false [get_files /home/dave/misc-projects/rftool-fpga/projects/rx_only/rx_only.srcs/sources_1/ip/iq_sample_fifo/iq_sample_fifo.dcp]
add_files -quiet /home/dave/misc-projects/rftool-fpga/projects/rx_only/rx_only.srcs/sources_1/ip/sys_pll/sys_pll.dcp
set_property used_in_implementation false [get_files /home/dave/misc-projects/rftool-fpga/projects/rx_only/rx_only.srcs/sources_1/ip/sys_pll/sys_pll.dcp]
add_files -quiet /home/dave/misc-projects/rftool-fpga/projects/rx_only/rx_only.srcs/sources_1/ip/ila_2/ila_2.dcp
set_property used_in_implementation false [get_files /home/dave/misc-projects/rftool-fpga/projects/rx_only/rx_only.srcs/sources_1/ip/ila_2/ila_2.dcp]
read_vhdl -library xil_defaultlib {
  /home/dave/misc-projects/rftool-fpga/pc/rx_packet_gen.vhd
  /home/dave/misc-projects/rftool-fpga/pc/pc_control_handler.vhd
  /home/dave/misc-projects/rftool-fpga/pc/ft60x_fifo_if.vhd
  /home/dave/misc-projects/rftool-fpga/ad9361/ad9361_spi_if.vhd
  /home/dave/misc-projects/rftool-fpga/ad9361/ad9361_rx_if.vhd
  /home/dave/misc-projects/rftool-fpga/projects/rx_only/rx_only.srcs/sources_1/new/rx_only_top.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/dave/misc-projects/rftool-fpga/projects/rx_only/rx_only.srcs/constrs_1/new/rftool_rev1.xdc
set_property used_in_implementation false [get_files /home/dave/misc-projects/rftool-fpga/projects/rx_only/rx_only.srcs/constrs_1/new/rftool_rev1.xdc]


synth_design -top rx_only_top -part xc7a50tftg256-2


write_checkpoint -force -noxdef rx_only_top.dcp

catch { report_utilization -file rx_only_top_utilization_synth.rpt -pb rx_only_top_utilization_synth.pb }
